name: pull_request

on:
  pull_request:
    branches: [main]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_OWNER: ${{ github.repository_owner }}

permissions: {}

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    timeout-minutes: 10
    container:
      image: ghcr.io/rancher/ci-image/nix:20260603-18
      options: --user suse
    permissions:
      contents: read
    steps:
      - name: Checkout
        # https://github.com/actions/checkout/releases
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0
      - name: 'Lint terraform'
        shell: >-
          /home/suse/.nix-profile/bin/nix develop
          --ignore-environment
          --extra-experimental-features nix-command
          --extra-experimental-features flakes
          --keep NIX_SSL_CERT_FILE
          --keep NIX_ENV_LOADED
          --keep TERM
          --keep HOME
          --keep SSH_AUTH_SOCK
          --keep GITHUB_TOKEN
          --keep GITHUB_OWNER
          --command bash -e {0}
        run: |
          terraform fmt -check -recursive -diff
          tflint --recursive

  eslint:
    name: 'Check GitHub scripts'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    container:
      image: ghcr.io/rancher/ci-image/nix:20260603-18
      options: --user suse
    permissions:
      contents: read
    steps:
      - name: Checkout
        # https://github.com/actions/checkout/releases
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0
      - name: 'Check for github-script errors'
        shell: >-
          /home/suse/.nix-profile/bin/nix develop
          --ignore-environment
          --extra-experimental-features nix-command
          --extra-experimental-features flakes
          --keep NIX_SSL_CERT_FILE
          --keep NIX_ENV_LOADED
          --keep TERM
          --keep HOME
          --keep SSH_AUTH_SOCK
          --keep GITHUB_TOKEN
          --keep GITHUB_OWNER
          --command bash -e {0}
        run: |
          npm install --save-dev eslint @eslint/js
          eslint .

  actionlint:
    name: 'Lint Workflows'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    container:
      image: ghcr.io/rancher/ci-image/nix:20260603-18
      options: --user suse
    permissions:
      contents: read
    steps:
      - name: Checkout
        # https://github.com/actions/checkout/releases
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0
      - name: 'Action Lint'
        shell: >-
          /home/suse/.nix-profile/bin/nix develop
          --ignore-environment
          --extra-experimental-features nix-command
          --extra-experimental-features flakes
          --keep NIX_SSL_CERT_FILE
          --keep NIX_ENV_LOADED
          --keep TERM
          --keep HOME
          --keep SSH_AUTH_SOCK
          --keep GITHUB_TOKEN
          --keep GITHUB_OWNER
          --command bash -e {0}
        run: |
          actionlint

  shellcheck:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    container:
      image: ghcr.io/rancher/ci-image/nix:20260603-18
      options: --user suse
    permissions:
      contents: read
    steps:
      - name: Checkout
        # https://github.com/actions/checkout/releases
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0
      - name: 'Shell Check'
        shell: >-
          /home/suse/.nix-profile/bin/nix develop
          --ignore-environment
          --extra-experimental-features nix-command
          --extra-experimental-features flakes
          --keep NIX_SSL_CERT_FILE
          --keep NIX_ENV_LOADED
          --keep TERM
          --keep HOME
          --keep SSH_AUTH_SOCK
          --keep GITHUB_TOKEN
          --keep GITHUB_OWNER
          --command bash -e {0}
        run: |
          while read -r file; do
            echo "checking $file..."
            shellcheck -x "$file"
          done <<<"$(grep -Rl -e '^#!' | grep -v '.terraform'| grep -v '.git')"

  validate-commit-message:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    container:
      image: ghcr.io/rancher/ci-image/nix:20260603-18
      options: --user suse
    permissions:
      contents: read
    steps:
      - name: Checkout
        # https://github.com/actions/checkout/releases
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: 'Check commit message'
        shell: >-
          /home/suse/.nix-profile/bin/nix develop
          --ignore-environment
          --extra-experimental-features nix-command
          --extra-experimental-features flakes
          --keep NIX_SSL_CERT_FILE
          --keep NIX_ENV_LOADED
          --keep TERM
          --keep HOME
          --keep SSH_AUTH_SOCK
          --keep GITHUB_TOKEN
          --keep GITHUB_OWNER
          --command bash -e {0}
        env:
          PR_NUMBER: ${{ github.event.number }}
        run: |
          bash .github/workflows/scripts/validate-commit-message.sh
  
  gitleaks:
    name: 'Scan for Secrets'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    container:
      image: ghcr.io/rancher/ci-image/nix:20260603-18
      options: --user suse
    permissions:
      contents: read
    steps:
      - name: Checkout
        # https://github.com/actions/checkout/releases
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0
      - name: 'Check for secrets'
        shell: >-
          /home/suse/.nix-profile/bin/nix develop
          --ignore-environment
          --extra-experimental-features nix-command
          --extra-experimental-features flakes
          --keep NIX_SSL_CERT_FILE
          --keep NIX_ENV_LOADED
          --keep TERM
          --keep HOME
          --keep SSH_AUTH_SOCK
          --keep GITHUB_TOKEN
          --keep GITHUB_OWNER
          --command bash -e {0}
        run: |
          gitleaks detect --no-banner -v --no-git
          gitleaks detect --no-banner -v
        continue-on-error: true

  test-compile-check:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    container:
      image: ghcr.io/rancher/ci-image/nix:20260603-18
      options: --user suse
    permissions:
      contents: read
    steps:
      - name: Checkout
        # https://github.com/actions/checkout/releases
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0
      - name: 'Test Compile Check'
        shell: >-
          /home/suse/.nix-profile/bin/nix develop
          --ignore-environment
          --extra-experimental-features nix-command
          --extra-experimental-features flakes
          --keep NIX_SSL_CERT_FILE
          --keep NIX_ENV_LOADED
          --keep TERM
          --keep HOME
          --keep SSH_AUTH_SOCK
          --keep GITHUB_TOKEN
          --keep GITHUB_OWNER
          --command bash -e {0}
        run: |
          cd test/tests
          go test -c
